<?php

return [
    'titles' => ['center' => '월말 정산 센터', 'detail' => '월말 정산 상세', 'failure_detail' => '월말 정산 실패 상세'],
    'labels' => ['current' => '월말 정산', 'historical' => '이전 월말 정산', 'unknown_agent' => '에이전시', 'pending' => '검토 대기', 'date_to' => '~'],
    'center' => [
        'description' => '완료된 주문의 프로모션 비용을 자동 집계하여 월말 정산을 생성하고 정산서의 검토 및 처리 진행 상황을 추적합니다.',
        'generate_latest' => '최신 정산 생성', 'cycle_configuration' => '정산 주기 설정',
        'cycle_description' => '경계일에 이전 주기를 마감하며 변경 사항은 다음 경계일부터 적용됩니다.',
        'boundary_day' => '월 경계일', 'trigger_time' => '실행 시간', 'confirm_old_config' => '미완료 주기는 기존 설정을 계속 사용함을 확인', 'save_next_config' => '다음 주기 설정 저장',
        'historical_heading' => '이전 정산 생성', 'historical_description' => '마감된 과거 주기를 선택하여 기존 생성·검토·정산 절차를 재사용합니다. 이미 존재하는 주기는 중복 생성하지 않습니다.', 'historical_period' => '과거 기준일', 'select_period' => '주기를 선택하세요', 'generate_historical' => '이전 정산 생성',
        'runs' => '정산 배치', 'period' => '주기', 'progress' => '진행', 'consumption_commission' => '소비/프로모션 비용', 'status' => '상태', 'manual' => '수동', 'historical_manual' => '과거 수동', 'scheduled' => '자동', 'failed_count' => '실패 :count건', 'dingtalk' => '딩톡: :status', 'view_failures' => '실패 :count건 보기', 'retry_failed' => '실패 항목 재시도', 'retry_dingtalk' => '딩톡 재시도', 'download_all' => '전체 다운로드', 'expand' => '펼치기', 'collapse' => '접기', 'empty' => '생성된 정산 배치가 없습니다.',
    ],
    'run_statuses' => ['queued' => '대기 중', 'running' => '처리 중', 'completed' => '생성 완료', 'partial_failed' => '일부 실패', 'failed' => '실패'],
    'notification_statuses' => ['pending' => '발송 대기', 'queued' => '대기열', 'sent' => '발송됨', 'failed' => '발송 실패', 'disabled' => '사용 안 함'],
    'settlement_statuses' => ['pending_review' => '검토 대기', 'rejected' => '반려됨', 'approved' => '승인됨', 'settled' => '정산 완료', 'paid' => '과거 지급 완료', 'reconciled' => '과거 대사 완료'],
    'detail' => [
        'back' => '월말 정산 센터로 돌아가기', 'generation_pending_heading' => '정산 상세가 아직 생성되지 않았습니다.', 'generation_pending_description' => '현재 소비 합계와 프로모션 비용 합계는 일시적으로 ₩0으로 표시됩니다. 먼저 정산 상세를 다시 생성하고 금액과 환율을 확인한 후 검토를 제출하세요.', 'regenerate_settlement' => '정산 상세 다시 생성', 'generation_unverified_heading' => '과거 정산 생성 상태를 확인할 수 없습니다.', 'generation_unverified_description' => '생성 배치, 상세 또는 정산 문서의 증거가 충분하지 않아 직접 검토할 수 없습니다. 슈퍼 관리자가 확인 근거를 입력하고 과거 가져오기로 보관하거나 복구 배치를 만들어 다시 생성하세요.', 'recovery_basis' => '확인 근거', 'create_recovery_batch' => '복구 배치 생성 및 다시 생성', 'recover_as_historical' => '과거 가져오기로 확인', 'recovery_batch_exists' => '복구 배치가 있습니다. 먼저 정산 상세를 다시 생성한 후 검토하세요.', 'historical_heading' => '과거 정산, 조회 전용', 'historical_description' => '이 기록은 과거 가져오기 또는 신규 정산 생성 대상 제외로 확인되어 다시 생성하거나 현재 검토 절차에 진입할 수 없습니다.', 'eyebrow' => '월말 정산 상세', 'previous' => '← 이전', 'next' => '다음 →', 'batch_navigation' => '동일 배치 정산 탐색', 'consumption_total' => '소비 합계', 'commission_total' => '프로모션 비용 합계', 'payable_cny' => '위안화 지급액', 'approve_heading' => '승인', 'quote_unavailable_hint' => '최신 시세를 사용할 수 없어 현재 환율을 유지했습니다. 수동으로 확인하거나 수정하세요.', 'quote_filled_hint' => 'API 시세를 자동 입력했습니다（매일 갱신, 시세 시각: :time）. 실제 정산 값에 맞게 수정할 수 있습니다.', 'quote_empty_hint' => '사용 가능한 시세가 없습니다. 정산 환율을 직접 입력하세요.', 'exchange_rate' => 'KRW/CNY 정산 환율', 'refresh_quote' => '최신 시세 가져오기', 'approve_generate' => '승인하고 Word/PDF 생성', 'reject_heading' => '반려', 'rejection_reason' => '문제 및 반려 사유', 'reject_settlement' => '정산 반려', 'settle' => '정보 확인 후 정산', 'controlled_correction' => '통제된 상태 수정', 'controlled_correction_description' => '슈퍼 관리자만 검토 대기·승인·정산 완료 사이의 상태를 수정할 수 있습니다. 과거 지급 완료 및 대사 완료 기록은 대상이 아닙니다. 검토 대기로 되돌리면 상세, 문서 및 집계가 취소되고 감사 기록이 남습니다. 화면 안내에 따라 상세를 다시 생성한 후 검토하세요.', 'target_status' => '대상 상태', 'correction_reason' => '수정 사유', 'submit_correction' => '상태 수정 제출', 'approved_status' => '승인됨', 'documents_regenerate' => '다시 생성', 'download_document' => ':format 다운로드', 'zero_order_hint' => '이 주기에 완료된 주문이 없어 주문 0건 정산을 정상 생성했습니다.', 'settlement_items' => '정산 상세 항목', 'order' => '주문', 'project_date' => '프로젝트/완료일', 'consumption' => '소비액', 'rate' => '요율', 'commission' => '프로모션 비용', 'items_empty' => '이 주기에 정산 상세 항목이 없습니다.', 'grade_suggestion' => '등급 조정 제안', 'grade_suggestion_description' => '이번 달 프로모션 비용은 ₩ :amount이며, 등급 #:current에서 #:recommended(으)로 조정하는 것을 제안합니다. 새 등급은 다음 달부터 적용됩니다.', 'review_note' => '검토 메모', 'approve_suggestion' => '제안 승인', 'keep_grade' => '기존 등급 유지', 'result' => '처리 결과: :status',
    ],
    'failure' => ['back' => '월말 정산 센터로 돌아가기', 'eyebrow' => '월말 정산 실패 상세', 'batch' => '배치 :id', 'download_report' => '실패 보고서 다운로드', 'retry_all' => '모든 실패 항목 재시도', 'run_status' => '배치 상태', 'total_agents' => '에이전시 수', 'success_count' => '성공 수', 'failed_count' => '실패 수', 'unresolved_heading' => '현재 해결되지 않은 실패 항목', 'no_failures' => '현재 해결되지 않은 실패 항목이 없습니다. 재시도에 성공했을 수 있습니다.', 'agent_code' => '에이전시 번호', 'agent_name' => '에이전시 이름', 'agent_id' => '에이전시 ID', 'reason' => '실패 사유'],
    'toasts' => ['retry_failed' => '실패한 에이전시 정산을 대기열에 다시 넣었습니다.', 'retry_notification' => '정산 완료 알림을 대기열에 다시 넣었습니다.', 'configuration_confirmation_required' => '미완료 정산이 있습니다. 저장하기 전에 현재 주기가 기존 설정을 계속 사용하는지 확인하세요.', 'configuration_saved' => '새 정산 주기 설정이 :date부터 적용됩니다.', 'created_and_dispatched' => ':label 배치 :id가 처리 대기열에 들어갔습니다.', 'created_and_completed' => ':label 배치 :id가 완료되었으며 처리할 에이전시가 없습니다.', 'created_partial_failed' => ':label 배치 :id가 생성되었지만 일부 에이전시 처리에 실패했습니다. 실패 항목을 재시도하세요.', 'existing_running' => '해당 주기에 처리 중인 정산 배치 :id가 이미 있어 중복 작업을 발송하지 않았습니다.', 'existing_completed' => '해당 주기에 완료된 정산 배치 :id가 이미 있어 중복 작업을 발송하지 않았습니다.', 'existing_partial_failed' => '해당 주기에 일부 실패한 배치 :id가 이미 있습니다. 실패 항목을 재시도하세요.', 'existing_other' => '해당 주기에 정산 배치 :id가 이미 있어 중복 작업을 발송하지 않았습니다.', 'rejected' => '정산을 반려했습니다.', 'approved' => '정산을 승인하고 Word/PDF를 생성했습니다.', 'quote_updated' => '최신 환율 시세를 갱신했습니다. 확인 후 검토를 제출하세요.', 'quote_failed_retained' => '최신 환율 시세 조회에 실패하여 기존 환율을 유지했습니다. 수동으로 확인하세요.', 'quote_unavailable' => '최신 환율 시세 조회에 실패했으며 사용 가능한 환율이 없습니다. 직접 입력하세요.', 'quote_error' => '최신 환율 시세 조회에 실패했습니다. 서비스를 확인한 후 다시 시도하세요.', 'settled' => '정산 완료를 확인했습니다.', 'corrected_to_review' => '정산을 검토 대기로 되돌렸습니다. 상세를 다시 생성하고 환율을 확인하세요.', 'corrected' => '정산 상태를 수정하고 감사 사유를 기록했습니다.', 'documents_regenerated' => 'Word/PDF를 다시 생성했습니다.', 'regeneration_unavailable' => '사용 가능한 배치가 있는 정산만 다시 생성할 수 있습니다. 먼저 과거 데이터를 확인하세요.', 'settlement_regenerated' => '정산 상세를 다시 생성했습니다.', 'historical_recovered' => '과거 정산을 대상 제외로 확인하고 감사 기록을 남겼습니다.', 'recovery_batch_created' => '복구 배치를 생성하고 정산 상세를 다시 생성했습니다.', 'suggestion_approved' => '등급 제안을 승인하고 다음 달 적용을 예약했습니다.', 'suggestion_rejected' => '등급 제안을 반려했습니다.', 'operation_failed' => '작업을 완료하지 못해 데이터를 롤백했습니다. 문서 생성 환경을 확인한 후 다시 시도하세요.', 'retry_all_failed' => '실패 항목을 처리 대기열에 다시 제출했습니다.'],
    'notifications' => ['title' => '정산 생성 완료', 'body' => "기간: :from ~ :to\n\n에이전시: :agents곳\n\n프로모션 비용 합계: ₩ :total"],
    'documents' => [
        'title' => '에이전시 월말 정산서', 'unknown' => '알 수 없음', 'unknown_agent' => '알 수 없는 에이전시',
        'agent' => '에이전시: :name（:code）', 'period' => '정산 기간: :from ~ :to',
        'headers' => ['order' => '주문', 'completed_on' => '완료일', 'project' => '프로젝트', 'consumption' => '소비액 KRW', 'rate' => '요율', 'commission' => '프로모션 비용 KRW'],
        'total_consumption' => '소비 합계: ₩ :amount', 'total_commission' => '프로모션 비용 합계: ₩ :amount',
        'exchange_rate' => '정산 환율: :rate KRW/CNY', 'payable' => '지급액: ¥ :amount',
        'filename' => '월말-정산서-:id.:format', 'archive_filename' => '월말-정산서-배치-:run.zip',
    ],
    'failure_report' => [
        'filename' => '월말-정산-실패-보고서-:id.xlsx', 'sheet' => '실패 상세',
        'headers' => ['batch' => '배치 번호', 'period' => '기간', 'agent_code' => '에이전시 번호', 'agent_name' => '에이전시 이름', 'agent_id' => '에이전시 ID', 'reason' => '실패 사유'],
    ],
];
