memory_limit=256M
max_execution_time=120
post_max_size=110M
upload_max_filesize=20M
date.timezone=Asia/Shanghai
expose_php=Off
opcache.enable=1
opcache.enable_cli=1
opcache.validate_timestamps=1
opcache.revalidate_freq=0
