<div>
    <x-page-back :href="route('reminders.index')" :label="__('reminders.create.back')" class="mb-4" />
    <section class="mb-5"><p class="text-xs font-medium text-zinc-400">{{ __('reminders.create.eyebrow') }}</p><h2 class="mt-1 text-2xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50">{{ __('reminders.titles.create') }}</h2><p class="mt-2 text-sm text-zinc-500 dark:text-zinc-400">{{ __('reminders.create.description') }}</p></section>
    <form wire:submit="save" class="max-w-3xl space-y-5 rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm dark:border-zinc-700 dark:bg-zinc-900">
        <div class="grid gap-4 sm:grid-cols-2"><flux:select wire:model.live="templateId" :label="__('reminders.create.template')"><flux:select.option value="">{{ __('reminders.create.without_template') }}</flux:select.option>@foreach ($templates as $template)<flux:select.option value="{{ $template->id }}">{{ $template->name }}</flux:select.option>@endforeach</flux:select><flux:select wire:model="customerId" :label="__('reminders.create.customer')" required><flux:select.option value="">{{ __('reminders.create.select_customer') }}</flux:select.option>@foreach ($customers as $customer)<flux:select.option value="{{ $customer->id }}">{{ $customer->name }}</flux:select.option>@endforeach</flux:select></div>
        <div class="grid gap-4 sm:grid-cols-2"><flux:input wire:model="title" :label="__('reminders.create.title')" required /><flux:select wire:model="assignedTo" :label="__('reminders.create.assignee')" required>@foreach ($users as $user)<flux:select.option value="{{ $user->id }}">{{ $user->name }}</flux:select.option>@endforeach</flux:select></div>
        <flux:input wire:model="dueAt" type="datetime-local" :label="__('reminders.create.due_at')" required />
        <flux:input wire:model="suggestion" :label="__('reminders.create.suggestion')" />
        <flux:textarea wire:model="notes" :label="__('reminders.create.notes')" rows="3" />
        <div class="grid gap-4 sm:grid-cols-2"><flux:select wire:model="recurrenceUnit" :label="__('reminders.create.recurrence')"><flux:select.option value="">{{ __('reminders.create.once') }}</flux:select.option><flux:select.option value="day">{{ __('reminders.create.day') }}</flux:select.option><flux:select.option value="week">{{ __('reminders.create.week') }}</flux:select.option><flux:select.option value="month">{{ __('reminders.create.month') }}</flux:select.option></flux:select><flux:input wire:model="recurrenceInterval" type="number" min="1" :label="__('reminders.create.interval')" /></div>
        <flux:checkbox wire:model.live="saveAsTemplate" :label="__('reminders.create.save_template')" />@if ($saveAsTemplate)<flux:input wire:model="templateName" :label="__('reminders.create.template_name')" required />@endif
        <flux:button type="submit" variant="primary">{{ __('reminders.create.submit') }}</flux:button>
    </form>
</div>
