<div>
    <section class="crm-section-header">
        <div><h2 class="text-2xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50">{{ __('reminders.titles.center') }}</h2><p class="mt-2 text-sm text-zinc-500 dark:text-zinc-400">{{ __('reminders.center.description') }}</p></div>
        <div class="flex gap-2"><flux:button :href="route('reminders.history')" variant="ghost" wire:navigate>{{ __('reminders.center.history') }}</flux:button><flux:button :href="route('reminders.create')" icon="plus" variant="primary" wire:navigate>{{ __('reminders.center.create') }}</flux:button></div>
    </section>

    @if ($stats)
        <section class="mb-6 grid gap-4 sm:grid-cols-3"><div class="rounded-xl border bg-white p-4 dark:bg-zinc-900"><span class="text-sm text-zinc-500">{{ __('reminders.center.pending') }}</span><strong class="mt-1 block text-2xl">{{ $stats['pending'] }}</strong></div><div class="rounded-xl border bg-white p-4 dark:bg-zinc-900"><span class="text-sm text-zinc-500">{{ __('reminders.center.overdue') }}</span><strong class="mt-1 block text-2xl text-red-600">{{ $stats['overdue'] }}</strong></div><div class="rounded-xl border bg-white p-4 dark:bg-zinc-900"><span class="text-sm text-zinc-500">{{ __('reminders.center.completed') }}</span><strong class="mt-1 block text-2xl">{{ $stats['completed'] }}</strong></div></section>
    @endif

    <section class="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm dark:border-zinc-700 dark:bg-zinc-900">
        <div class="mb-4 max-w-xs"><flux:select wire:model.live="type" :label="__('reminders.center.type')"><flux:select.option value="">{{ __('reminders.center.all_types') }}</flux:select.option><flux:select.option value="appointment">{{ __('reminders.center.appointment') }}</flux:select.option><flux:select.option value="post_treatment">{{ __('reminders.center.post_treatment') }}</flux:select.option><flux:select.option value="date_offset">{{ __('reminders.center.date_offset') }}</flux:select.option><flux:select.option value="fixed_cycle">{{ __('reminders.center.fixed_cycle') }}</flux:select.option><flux:select.option value="custom">{{ __('reminders.center.custom') }}</flux:select></flux:select></div>
        <div class="space-y-4">
            @forelse ($reminders as $reminder)
                <article class="rounded-xl border border-zinc-200 p-4 dark:border-zinc-700">
                    <div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="font-semibold">{{ $reminder->title }}</h3><p class="mt-1 text-sm"><span class="font-semibold">{{ $customerNames[$reminder->customer_id] ?? __('reminders.center.unknown_customer') }}</span> · {{ $reminder->due_at->format('Y-m-d H:i') }}</p><p class="mt-1 text-sm text-zinc-500">{{ $reminder->suggestion ?: __('reminders.center.no_script') }}</p></div><span class="crm-pill {{ $reminder->due_at->isPast() ? 'tone-red' : 'tone-amber' }}">{{ $reminder->due_at->isPast() ? __('reminders.center.due') : __('reminders.center.pending') }}</span></div>
                    <div class="mt-4 grid gap-3 lg:grid-cols-4"><flux:input wire:model="actionNotes" :label="__('reminders.center.complete_notes')" /><flux:input wire:model="snoozeUntil" type="datetime-local" :label="__('reminders.center.snooze_until')" /><flux:input wire:model="snoozeReason" :label="__('reminders.center.snooze_reason')" /><flux:select wire:model="assigneeId" :label="__('reminders.center.transfer_to')"><flux:select.option value="">{{ __('reminders.center.select') }}</flux:select.option>@foreach ($users as $user)<flux:select.option value="{{ $user->id }}">{{ $user->name }}</flux:select.option>@endforeach</flux:select></div>
                    <div class="mt-3 flex flex-wrap gap-2"><flux:button wire:click="complete({{ $reminder->id }})" size="sm">{{ __('reminders.center.mark_complete') }}</flux:button><flux:button wire:click="snooze({{ $reminder->id }})" size="sm" variant="ghost">{{ __('reminders.center.snooze') }}</flux:button><flux:button wire:click="transfer({{ $reminder->id }})" size="sm" variant="ghost">{{ __('reminders.center.transfer') }}</flux:button><flux:button wire:click="cancel({{ $reminder->id }})" size="sm" variant="ghost">{{ __('reminders.center.cancel') }}</flux:button>@if (in_array($reminder->notification_status, ['failed', 'disabled'], true))<flux:button wire:click="retryNotification({{ $reminder->id }})" size="sm" variant="ghost">{{ __('reminders.center.retry_notification') }}</flux:button>@endif<span class="ml-auto text-xs text-zinc-500">{{ __('reminders.center.dingtalk', ['status' => __('reminders.notification_statuses.'.$reminder->notification_status)]) }}</span></div>
                </article>
            @empty<p class="py-10 text-center text-zinc-500">{{ __('reminders.center.empty') }}</p>@endforelse
        </div>
        <div class="mt-5">{{ $reminders->links() }}</div>
    </section>
</div>
