<div>
    <x-page-back :href="route('configuration.index')" :label="__('reminders.configuration.back')" class="mb-4" />
    <section class="mb-5"><p class="text-xs font-medium text-zinc-400">{{ __('reminders.configuration.eyebrow') }}</p><h2 class="mt-1 text-2xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50">{{ __('reminders.configuration.heading') }}</h2><p class="mt-2 text-sm text-zinc-500 dark:text-zinc-400">{{ __('reminders.configuration.description') }}</p></section>
    <div class="mb-5 rounded-xl border px-4 py-3 text-sm {{ $dingtalkEnabled ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : 'border-amber-200 bg-amber-50 text-amber-800' }}">{{ __('reminders.configuration.dingtalk', ['status' => $dingtalkEnabled ? __('reminders.configuration.enabled') : __('reminders.configuration.disabled_hint')]) }}</div>

    <section class="grid gap-6 xl:grid-cols-2">
        <div class="rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-700 dark:bg-zinc-900">
            <h3 class="font-semibold">{{ __('reminders.configuration.new_rule') }}</h3>
            <form wire:submit="saveRule" class="mt-4 space-y-3">
                <div class="grid gap-3 sm:grid-cols-2"><flux:input wire:model="ruleName" :label="__('reminders.configuration.rule_name')" required /><flux:input wire:model="ruleTitle" :label="__('reminders.configuration.title')" required /></div>
                <div class="grid gap-3 sm:grid-cols-2"><flux:select wire:model.live="triggerType" :label="__('reminders.configuration.trigger_type')"><flux:select.option value="date_offset">{{ __('reminders.configuration.date_offset') }}</flux:select.option><flux:select.option value="status_change">{{ __('reminders.configuration.status_change') }}</flux:select.option><flux:select.option value="fixed_cycle">{{ __('reminders.configuration.fixed_cycle') }}</flux:select.option><flux:select.option value="holiday_date">{{ __('reminders.configuration.holiday_date') }}</flux:select.option><flux:select.option value="manual">{{ __('reminders.configuration.manual') }}</flux:select.option></flux:select><x-date-time-picker wire:model="triggerTime" :value="$triggerTime" mode="time" :label="__('reminders.configuration.trigger_time')" /></div>
                @if ($triggerType === 'date_offset')<div class="grid gap-3 sm:grid-cols-2"><flux:select wire:model="dateField" :label="__('reminders.configuration.date_field')"><flux:select.option value="created_at">{{ __('reminders.configuration.created_at') }}</flux:select.option><flux:select.option value="appointment_at">{{ __('reminders.configuration.appointment_at') }}</flux:select.option><flux:select.option value="completed_on">{{ __('reminders.configuration.completed_on') }}</flux:select.option><flux:select.option value="birth_date">{{ __('reminders.configuration.birth_date') }}</flux:select.option><flux:select.option value="wechat_added_on">{{ __('reminders.configuration.wechat_added_on') }}</flux:select.option></flux:select><flux:input wire:model="offsetDays" type="number" :label="__('reminders.configuration.offset_days')" /></div>@endif
                @if ($triggerType === 'fixed_cycle')<flux:input wire:model="intervalDays" type="number" min="1" :label="__('reminders.configuration.interval_days')" />@endif
                @if ($triggerType === 'holiday_date')<x-date-time-picker wire:model="holidayDate" :value="$holidayDate" :label="__('reminders.configuration.holiday_date_value')" required />@endif
                <div class="grid gap-3 sm:grid-cols-2"><flux:select wire:model="scopeType" :label="__('reminders.configuration.scope')"><flux:select.option value="all_customers">{{ __('reminders.configuration.all_customers') }}</flux:select.option><flux:select.option value="agent">{{ __('reminders.configuration.agent') }}</flux:select.option><flux:select.option value="project">{{ __('reminders.configuration.project') }}</flux:select.option><flux:select.option value="owner">{{ __('reminders.configuration.owner') }}</flux:select.option><flux:select.option value="cooperation_status">{{ __('reminders.configuration.cooperation_status') }}</flux:select.option></flux:select><flux:input wire:model="scopeValue" :label="__('reminders.configuration.scope_value')" /></div>
                <div class="grid gap-3 sm:grid-cols-2"><flux:input wire:model="suggestion" :label="__('reminders.configuration.suggestion')" /><flux:input wire:model="priority" type="number" min="1" max="5" :label="__('reminders.configuration.priority')" /></div>
                <flux:button type="submit">{{ $editingRuleId ? __('reminders.configuration.save_rule_edit') : __('reminders.configuration.save_rule') }}</flux:button>
            </form>
        </div>
        <div class="rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-700 dark:bg-zinc-900">
            <h3 class="font-semibold">{{ __('reminders.configuration.global_templates') }}</h3>
            <form wire:submit="saveTemplate" class="mt-4 space-y-3"><flux:input wire:model="templateName" :label="__('reminders.configuration.template_name')" required /><flux:input wire:model="templateTitle" :label="__('reminders.configuration.title')" required /><flux:input wire:model="templateSuggestion" :label="__('reminders.configuration.template_suggestion')" /><flux:button type="submit">{{ __('reminders.configuration.add_template') }}</flux:button></form>
            <div class="crm-table-wrap mt-5"><table class="crm-table"><thead><tr><th>{{ __('reminders.configuration.template') }}</th><th>{{ __('reminders.configuration.type') }}</th><th>{{ __('reminders.configuration.status') }}</th><th></th></tr></thead><tbody>@foreach ($templates as $template)<tr><td class="font-semibold">{{ $template->name }}</td><td>{{ $template->is_system ? __('reminders.configuration.system') : __('reminders.configuration.global') }}</td><td>{{ $template->is_active ? __('reminders.configuration.enabled_status') : __('reminders.configuration.disabled_status') }}</td><td><div class="flex gap-1"><flux:button wire:click="editTemplate({{ $template->id }})" size="sm" variant="ghost">{{ __('reminders.configuration.edit') }}</flux:button><flux:button wire:click="copyTemplate({{ $template->id }})" size="sm" variant="ghost">{{ __('reminders.configuration.copy') }}</flux:button><flux:button wire:click="toggleTemplate({{ $template->id }})" size="sm" variant="ghost">{{ $template->is_active ? __('reminders.configuration.disable') : __('reminders.configuration.enable') }}</flux:button></div></td></tr>@endforeach</tbody></table></div>
        </div>
    </section>
    <section class="mt-6 rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-700 dark:bg-zinc-900"><h3 class="font-semibold">{{ __('reminders.configuration.configured_rules') }}</h3><div class="crm-table-wrap mt-4"><table class="crm-table"><thead><tr><th>{{ __('reminders.configuration.rule_name') }}</th><th>{{ __('reminders.configuration.trigger_scope') }}</th><th>{{ __('reminders.configuration.status') }}</th><th></th></tr></thead><tbody>@forelse ($rules as $rule)<tr><td class="font-semibold">{{ $rule->name }}<div class="text-xs text-zinc-500">{{ $rule->title }}</div></td><td>{{ __('reminders.trigger_types.'.$rule->trigger_type) }} / {{ __('reminders.scope_types.'.$rule->scope_type) }}</td><td>{{ $rule->is_active ? __('reminders.configuration.enabled_status') : __('reminders.configuration.disabled_status') }}</td><td><div class="flex gap-1"><flux:button wire:click="editRule({{ $rule->id }})" size="sm" variant="ghost">{{ __('reminders.configuration.edit') }}</flux:button><flux:button wire:click="toggleRule({{ $rule->id }})" size="sm" variant="ghost">{{ $rule->is_active ? __('reminders.configuration.disable') : __('reminders.configuration.enable') }}</flux:button></div></td></tr>@empty<tr><td colspan="4" class="py-8 text-center text-zinc-500">{{ __('reminders.configuration.empty') }}</td></tr>@endforelse</tbody></table></div></section>
</div>
